language: python
python:
  - "3.5"
before_install:
  - sudo apt-get update
  - sudo apt-get install libcurl4-gnutls-dev librtmp-dev
install:
  - pip install pycurl flake8
  - pip install mock
  - python setup.py install
script:
  - python -W always setup.py test
